# Generated by Django 6.0.4 on 2026-05-27 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='secondsPlayed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='src',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
