# Generated by Django 6.0.4 on 2026-05-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_secondsplayed_song_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='secondsPlayed',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='src',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
