# Generated by Django 6.0.4 on 2026-05-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_secondsplayed_alter_song_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='secondsPlayed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
