# Generated by Django 6.0.4 on 2026-06-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
