# Generated by Django 6.0.4 on 2026-06-02 18:43

from django.db import migrations
from mutagen.mp3 import MP3
import os

def get_duration(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')

    for song in Song.objects.all():
        loc = f"C:/Users/comsc/OneDrive/Desktop/Personal Projects/Corphicient/backend/" + song.src
        print(loc)
        print(os.path.exists(loc))
        song.duration = MP3(loc).info.length
        song.save(update_fields=['duration'])


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_duration'),
    ]

    operations = [
        migrations.RunPython(get_duration)
    ]
