# Generated by Django 6.0.4 on 2026-06-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_get_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
