# Generated by Django 6.0.4 on 2026-07-03 02:12

from django.db import migrations
import os
import yt_dlp

def redownload_songs(apps, schema_editor):
    Song = apps.get_model('songs', 'Song')
    existing_songs = os.listdir("C:/Users/comsc/OneDrive/Desktop/Personal Projects/Corphicient/backend/media/songs")

    for song in Song.objects.all():
        src = song.src.split("/")[-1]
        if src not in existing_songs:
            download_song(song.href, name=song.name)

def download_song(url, name="New Song", output_dir="../backend/media/songs/"):
    downloaded_path = {}

    def postprocessor_hook(d):
        if d["status"] == "finished":
            downloaded_path["filename"] = d["info_dict"]["filepath"]

    ydl_opts = {
        "format": "bestaudio[ext=mp3]/bestaudio",
        "postprocessors": [{
            "key": "FFmpegExtractAudio",
            "preferredcodec": "mp3",
        }],
        "outtmpl": f"{output_dir}/{name}.%(ext)s",
        "postprocessor_hooks": [postprocessor_hook],
    }
    try:
        with yt_dlp.YoutubeDL(ydl_opts) as ydl:
            info = ydl.extract_info(url, download=True)
            sanitized_info = ydl.sanitize_info(info)
            return True
    except Exception as e:
        print(f"\n\n\nException while downloading song: \n\n{e}")
        return {
            "location": "",
            "duration": 0
        }


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_alter_song_duration'),
    ]

    operations = [
        migrations.RunPython(redownload_songs)
    ]

