# Generated by Django 6.0.3 on 2026-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0010_song_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='color',
            field=models.CharField(default='#44BBBB', max_length=7),
        ),
    ]
