# Generated by Django 6.0.3 on 2026-08-01 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0011_song_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='color',
            field=models.CharField(default='#44BBBB', max_length=15),
        ),
    ]
