# Generated by Django 6.0.3 on 2026-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0012_alter_song_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='secondsPlayed',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
