# Generated by Django 6.0.3 on 2026-10-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_alter_song_secondsplayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
