# Generated by Django 6.0.3 on 2026-10-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0016_auto_20261004_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(default='', max_length=50),
        ),
    ]
