# Generated by Django 6.0.3 on 2026-07-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='color',
            field=models.CharField(default='#44BBBB', max_length=7),
        ),
    ]
