# Generated by Django 6.0.3 on 2026-09-06 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_note_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.section')),
            ],
            options={
                'ordering': ['order'],
                'constraints': [models.UniqueConstraint(fields=('section', 'note'), name='unique_section_note')],
            },
        ),
    ]
