# Generated by Django 6.0.3 on 2026-09-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20260906_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='notes',
        ),
        migrations.AddField(
            model_name='section',
            name='notes',
            field=models.ManyToManyField(
                blank=True,
                through='notes.SectionNote',
                to='notes.note',
            ),
        ),
    ]
